package database

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"log/slog"
	"os"
	"strconv"
	"time"

	"visory/internal/database/logs"
	"visory/internal/database/notifications"
	"visory/internal/database/sessions"
	"visory/internal/database/user"

	_ "github.com/mattn/go-sqlite3"
	"github.com/pressly/goose/v3"
)

//go:embed migrations/*.sql
var embedMigrations embed.FS

func Migrate(db *sql.DB) error {
	// setup database
	goose.SetBaseFS(embedMigrations)
	if err := goose.SetDialect(string(goose.DialectSQLite3)); err != nil {
		return err
	}

	if err := goose.Up(db, "migrations"); err != nil {
		return err
	}
	return nil
}

type Service struct {
	db           *sql.DB
	User         *user.Queries // Assuming user.Queries is a struct generated by sqlc for user-related queries
	Session      *sessions.Queries
	Log          *logs.Queries
	Notification *notifications.Queries
}

func New() *Service {
	database := os.Getenv("BLUEPRINT_DB_DATABASE")
	if database == "" {
		slog.Error("Database environment variable not set", "variable", "BLUEPRINT_DB_DATABASE")
		panic("environment variable BLUEPRINT_DB_DATABASE is not set")
	}
	db, err := sql.Open("sqlite3", database)
	if err != nil {
		slog.Error("Failed to open database connection", "error", err)
		panic(fmt.Sprintf("failed to open database connection: %s", err))
	}
	err = Migrate(db)
	if err != nil {
		slog.Error("Failed to run database migrations", "error", err)
		panic(fmt.Sprintf("failed to run database migrations: %s", err))
	}

	dbInstance := &Service{
		db:           db,
		User:         user.New(db),
		Session:      sessions.New(db),
		Log:          logs.New(db),
		Notification: notifications.New(db),
	}
	return dbInstance
}

// Health checks the health of the database connection by pinging the database.
// It returns a map with keys indicating various health statistics.
func (s *Service) Health() map[string]string {
	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()

	stats := make(map[string]string)

	// Ping the database
	err := s.db.PingContext(ctx)
	if err != nil {
		stats["status"] = "down"
		stats["error"] = fmt.Sprintf("db down: %v", err)
		slog.Error("Database ping failed", "error", err)
		return stats
	}

	// Database is up, add more statistics
	stats["status"] = "up"
	stats["message"] = "It's healthy"

	// Get database stats (like open connections, in use, idle, etc.)
	dbStats := s.db.Stats()
	stats["open_connections"] = strconv.Itoa(dbStats.OpenConnections)
	stats["in_use"] = strconv.Itoa(dbStats.InUse)
	stats["idle"] = strconv.Itoa(dbStats.Idle)
	stats["wait_count"] = strconv.FormatInt(dbStats.WaitCount, 10)
	stats["wait_duration"] = dbStats.WaitDuration.String()
	stats["max_idle_closed"] = strconv.FormatInt(dbStats.MaxIdleClosed, 10)
	stats["max_lifetime_closed"] = strconv.FormatInt(dbStats.MaxLifetimeClosed, 10)

	// Evaluate stats to provide a health message
	if dbStats.OpenConnections > 40 { // Assuming 50 is the max for this example
		stats["message"] = "The database is experiencing heavy load."
	}

	if dbStats.WaitCount > 1000 {
		stats["message"] = "The database has a high number of wait events, indicating potential bottlenecks."
	}

	if dbStats.MaxIdleClosed > int64(dbStats.OpenConnections)/2 {
		stats["message"] = "Many idle connections are being closed, consider revising the connection pool settings."
	}

	if dbStats.MaxLifetimeClosed > int64(dbStats.OpenConnections)/2 {
		stats["message"] = "Many connections are being closed due to max lifetime, consider increasing max lifetime or revising the connection usage pattern."
	}

	return stats
}

// Close closes the database connection.
// It logs a message indicating the disconnection from the specific database.
// If the connection is successfully closed, it returns nil.
// If an error occurs while closing the connection, it returns the error.
func (s *Service) Close() error {
	slog.Info("Closing database connection")
	return s.db.Close()
}
