/**
 * this is just to mimic the echo error structure
 * eg: {"message":"Failed to list virtual-machines"}
 * reprod: echo.NewHTTPError(http.StatusInternalServerError, "Failed to list virtual-machines").SetInternal(fmt.Errorf("database connection error"))
 */
export interface HTTPError {
  message: string;
}
export interface StorageDevice {
  name: string;
  size: string;
  size_bytes: number /* int64 */;
  type: string;
  mount_point: string;
  usage_percent: number /* int32 */;
}
export interface MountPoint {
  path: string;
  device: string;
  fs_type: string;
  total: number /* int64 */;
  used: number /* int64 */;
  available: number /* int64 */;
  use_percent: number /* int32 */;
}
export interface EnvVars {
  Port: string;
  AppEnv: string;
  DBPath: string;
  APP_VERSION: string;
  GoogleOAuthKey: string;
  GoogleOAuthSecret: string;
  GithubOAuthKey: string;
  GithubOAuthSecret: string;
  /**
   * OAuthCallbackURL  string `envconfig:"OAUTH_CALLBACK_URL" default:"http://localhost:9999/api/auth/oauth/callback" required:"true"`
   */
  BaseUrl: string;
  SessionSecret: string;
  FRONTEND_DASH: string;
  BaseUrlWithPort: string;
}
export const COOKIE_NAME = "token";
export const BYPASS_RBAC_HEADER = "X-Bypass-RBAC";
export interface Login {
  username: string;
  password: string;
}
export type RBACPolicy = string;
export const RBAC_DOCKER_READ: RBACPolicy = "docker_read";
export const RBAC_DOCKER_WRITE: RBACPolicy = "docker_write";
export const RBAC_DOCKER_UPDATE: RBACPolicy = "docker_update";
export const RBAC_DOCKER_DELETE: RBACPolicy = "docker_delete";
export const RBAC_QEMU_READ: RBACPolicy = "qemu_read";
export const RBAC_QEMU_WRITE: RBACPolicy = "qemu_write";
export const RBAC_QEMU_UPDATE: RBACPolicy = "qemu_update";
export const RBAC_QEMU_DELETE: RBACPolicy = "qemu_delete";
export const RBAC_EVENT_VIEWER: RBACPolicy = "event_viewer";
export const RBAC_EVENT_MANAGER: RBACPolicy = "event_manager";
export const RBAC_USER_ADMIN: RBACPolicy = "user_admin";
export const RBAC_SETTINGS_MANAGER: RBACPolicy = "settings_manager";
export const RBAC_AUDIT_LOG_VIEWER: RBACPolicy = "audit_log_viewer";
export const RBAC_HEALTH_CHECKER: RBACPolicy = "health_checker";
export interface UpsertSessionParams {
  user_id: number /* int64 */;
  session_token: string;
}
export interface Service {
  User?: any /* user.Queries */; // Assuming user.Queries is a struct generated by sqlc for user-related queries
  Session?: any /* sessions.Queries */;
  Log?: any /* logs.Queries */;
  Notification?: any /* notifications.Queries */;
}
export interface Health {
  status: string;
  message: string;
  app_version: string;
  base_url: string;
  error?: string;
  stats: HealthStats;
}
export interface HealthStats {
  open_connections: number /* int */;
  in_use: number /* int */;
  idle: number /* int */;
  wait_count: number /* int64 */;
  wait_duration: string;
  max_idle_closed: number /* int64 */;
  max_lifetime_closed: number /* int64 */;
}
export interface CreateUserParams {
  username: string;
  email: string;
  password: string;
  role: string;
}
export interface GetByEmailOrUsernameParams {
  email: string;
  username: string;
}
export interface GetUserAndSessionByTokenRow {
  user: User;
  user_session: UserSession;
}
export interface UpdateUserParams {
  username: string;
  email: string;
  role: string;
  id: number /* int64 */;
}
export interface UpdateUserPasswordParams {
  password: string;
  id: number /* int64 */;
}
export interface UpdateUserRoleParams {
  role: string;
  id: number /* int64 */;
}
export interface UpsertUserParams {
  username: string;
  email: string;
  password: string;
  role: string;
}
export interface Log {
  id: number /* int64 */;
  user_id: number /* int64 */;
  action: string;
  details?: string;
  created_at: string;
}
export interface Notification {
  id: number /* int64 */;
  user_id: number /* int64 */;
  message: string;
  read?: boolean;
  created_at: string;
  updated_at: string;
}
export interface User {
  id: number /* int64 */;
  username: string;
  email: string;
  password: string;
  role: string;
  created_at: string;
  updated_at: string;
}
export interface UserSession {
  id: number /* int64 */;
  user_id: number /* int64 */;
  session_token: string;
  created_at: string;
  updated_at: string;
}
