export interface EnvVars {
  Port: string;
  AppEnv: string;
  DBPath: string;
}
export interface UpsertSessionParams {
  user_id: number /* int64 */;
  session_token: string;
}
export interface Service {
  User?: any /* user.Queries */; // Assuming user.Queries is a struct generated by sqlc for user-related queries
  Session?: any /* sessions.Queries */;
  Log?: any /* logs.Queries */;
  Notification?: any /* notifications.Queries */;
}
export interface Health {
  status: string;
  message: string;
  error?: string;
  stats?: HealthStats;
}
export interface HealthStats {
  open_connections: number /* int */;
  in_use: number /* int */;
  idle: number /* int */;
  wait_count: number /* int64 */;
  wait_duration: string;
  max_idle_closed: number /* int64 */;
  max_lifetime_closed: number /* int64 */;
}
export interface GetByEmailOrUsernameParams {
  email: string;
  username: string;
}
export interface UpsertUserParams {
  username: string;
  email: string;
  password: string;
  role: string;
}
export interface Log {
  id: number /* int64 */;
  user_id: number /* int64 */;
  action: string;
  details?: string;
  created_at: Date;
}
export interface Notification {
  id: number /* int64 */;
  user_id: number /* int64 */;
  message: string;
  read?: boolean;
  created_at: Date;
  updated_at: Date;
}
export interface User {
  id: number /* int64 */;
  username: string;
  email: string;
  password: string;
  role: string;
  created_at: Date;
  updated_at: Date;
}
export interface UserSession {
  id: number /* int64 */;
  user_id: number /* int64 */;
  session_token: string;
  created_at: Date;
  updated_at: Date;
}
