// Generated by ts-to-zod
import { z } from "zod";

export const httpErrorSchema = z.object({
  message: z.string(),
});

export const storageDeviceSchema = z.object({
  name: z.string(),
  size: z.string(),
  size_bytes: z.number(),
  type: z.string(),
  mount_point: z.string(),
  usage_percent: z.number(),
});

export const mountPointSchema = z.object({
  path: z.string(),
  device: z.string(),
  fs_type: z.string(),
  total: z.number(),
  used: z.number(),
  available: z.number(),
  use_percent: z.number(),
});

export const envVarsSchema = z.object({
  Port: z.string(),
  AppEnv: z.string(),
  DBPath: z.string(),
  APP_VERSION: z.string(),
  GoogleOAuthKey: z.string(),
  GoogleOAuthSecret: z.string(),
  GithubOAuthKey: z.string(),
  GithubOAuthSecret: z.string(),
  BaseUrl: z.string(),
  SessionSecret: z.string(),
  FRONTEND_DASH: z.string(),
  BaseUrlWithPort: z.string(),
});

export const loginSchema = z.object({
  username: z.string(),
  password: z.string(),
});

export const rbacPolicySchema = z.string();

export const upsertSessionParamsSchema = z.object({
  user_id: z.number(),
  session_token: z.string(),
});

export const serviceSchema = z.object({
  User: z.any().optional(),
  Session: z.any().optional(),
  Log: z.any().optional(),
  Notification: z.any().optional(),
});

export const healthStatsSchema = z.object({
  open_connections: z.number(),
  in_use: z.number(),
  idle: z.number(),
  wait_count: z.number(),
  wait_duration: z.string(),
  max_idle_closed: z.number(),
  max_lifetime_closed: z.number(),
});

export const getByEmailOrUsernameParamsSchema = z.object({
  email: z.string(),
  username: z.string(),
});

export const userSchema = z.object({
  id: z.number(),
  username: z.string(),
  email: z.string(),
  password: z.string(),
  role: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const userSessionSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  session_token: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const upsertUserParamsSchema = z.object({
  username: z.string(),
  email: z.string(),
  password: z.string(),
  role: z.string(),
});

export const logSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  action: z.string(),
  details: z.string().optional(),
  created_at: z.string(),
});

export const notificationSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  message: z.string(),
  read: z.boolean().optional(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const healthSchema = z.object({
  status: z.string(),
  message: z.string(),
  app_version: z.string(),
  base_url: z.string(),
  error: z.string().optional(),
  stats: healthStatsSchema,
});

export const getUserAndSessionByTokenRowSchema = z.object({
  user: userSchema,
  user_session: userSessionSchema,
});
