// Generated by ts-to-zod
import { z } from "zod";

export const httpErrorSchema = z.object({
  message: z.string(),
});

export const envVarsSchema = z.object({
  Port: z.string(),
  AppEnv: z.string(),
  DBPath: z.string(),
});

export const loginSchema = z.object({
  username: z.string(),
  password: z.string(),
});

export const upsertSessionParamsSchema = z.object({
  user_id: z.number(),
  session_token: z.string(),
});

export const serviceSchema = z.object({
  User: z.any().optional(),
  Session: z.any().optional(),
  Log: z.any().optional(),
  Notification: z.any().optional(),
});

export const healthStatsSchema = z.object({
  open_connections: z.number(),
  in_use: z.number(),
  idle: z.number(),
  wait_count: z.number(),
  wait_duration: z.string(),
  max_idle_closed: z.number(),
  max_lifetime_closed: z.number(),
});

export const getByEmailOrUsernameParamsSchema = z.object({
  email: z.string(),
  username: z.string(),
});

export const upsertUserParamsSchema = z.object({
  username: z.string(),
  email: z.string(),
  password: z.string(),
  role: z.string(),
});

export const logSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  action: z.string(),
  details: z.string().optional(),
  created_at: z.date(),
});

export const notificationSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  message: z.string(),
  read: z.boolean().optional(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const userSchema = z.object({
  id: z.number(),
  username: z.string(),
  email: z.string(),
  password: z.string(),
  role: z.string(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const userSessionSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  session_token: z.string(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const healthSchema = z.object({
  status: z.string(),
  message: z.string(),
  error: z.string().optional(),
  stats: healthStatsSchema,
});
