// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/docs/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/sys/networking": {
    params: {};
  };
  "/app/sys/settings": {
    params: {};
  };
  "/app/sys/storage": {
    params: {};
  };
  "/app/dashboard": {
    params: {};
  };
  "/app/sys/users": {
    params: {};
  };
  "/app/templates": {
    params: {};
  };
  "/app/sys/logs": {
    params: {};
  };
  "/app/monitor": {
    params: {};
  };
  "/app/docker": {
    params: {};
  };
  "/app/iso": {
    params: {};
  };
  "/app/vms": {
    params: {};
  };
  "/app/vms/:uuid/console": {
    params: {
      "uuid": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/auth/register" | "/auth/login" | "/docs" | "/docs/*" | "/app" | "/app/sys/networking" | "/app/sys/settings" | "/app/sys/storage" | "/app/dashboard" | "/app/sys/users" | "/app/templates" | "/app/sys/logs" | "/app/monitor" | "/app/docker" | "/app/iso" | "/app/vms" | "/app/vms/:uuid/console";
  };
  "routes/_landing.tsx": {
    id: "routes/_landing";
    page: "/";
  };
  "routes/_landing._index.tsx": {
    id: "routes/_landing._index";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth" | "/auth/register" | "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs" | "/docs/*";
  };
  "routes/docs._index.tsx": {
    id: "routes/docs._index";
    page: "/docs";
  };
  "routes/docs.$.tsx": {
    id: "routes/docs.$";
    page: "/docs/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/sys/networking" | "/app/sys/settings" | "/app/sys/storage" | "/app/dashboard" | "/app/sys/users" | "/app/templates" | "/app/sys/logs" | "/app/monitor" | "/app/docker" | "/app/iso" | "/app/vms" | "/app/vms/:uuid/console";
  };
  "routes/app.sys.networking.tsx": {
    id: "routes/app.sys.networking";
    page: "/app/sys/networking";
  };
  "routes/app.sys.settings.tsx": {
    id: "routes/app.sys.settings";
    page: "/app/sys/settings";
  };
  "routes/app.sys.storage/route.tsx": {
    id: "routes/app.sys.storage";
    page: "/app/sys/storage";
  };
  "routes/app.dashboard.tsx": {
    id: "routes/app.dashboard";
    page: "/app/dashboard";
  };
  "routes/app.sys.users/route.tsx": {
    id: "routes/app.sys.users";
    page: "/app/sys/users";
  };
  "routes/app.templates/route.tsx": {
    id: "routes/app.templates";
    page: "/app/templates";
  };
  "routes/app.sys.logs/route.tsx": {
    id: "routes/app.sys.logs";
    page: "/app/sys/logs";
  };
  "routes/app.monitor.tsx": {
    id: "routes/app.monitor";
    page: "/app/monitor";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.docker/route.tsx": {
    id: "routes/app.docker";
    page: "/app/docker";
  };
  "routes/app.iso.tsx": {
    id: "routes/app.iso";
    page: "/app/iso";
  };
  "routes/app.vms.tsx": {
    id: "routes/app.vms";
    page: "/app/vms" | "/app/vms/:uuid/console";
  };
  "routes/app.vms.$uuid.console.tsx": {
    id: "routes/app.vms.$uuid.console";
    page: "/app/vms/:uuid/console";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_landing": typeof import("./src/routes/_landing.tsx");
  "routes/_landing._index": typeof import("./src/routes/_landing._index.tsx");
  "routes/auth": typeof import("./src/routes/auth.tsx");
  "routes/auth.register": typeof import("./src/routes/auth.register.tsx");
  "routes/auth.login": typeof import("./src/routes/auth.login.tsx");
  "routes/docs": typeof import("./src/routes/docs.tsx");
  "routes/docs._index": typeof import("./src/routes/docs._index.tsx");
  "routes/docs.$": typeof import("./src/routes/docs.$.tsx");
  "routes/app": typeof import("./src/routes/app.tsx");
  "routes/app.sys.networking": typeof import("./src/routes/app.sys.networking.tsx");
  "routes/app.sys.settings": typeof import("./src/routes/app.sys.settings.tsx");
  "routes/app.sys.storage": typeof import("./src/routes/app.sys.storage/route.tsx");
  "routes/app.dashboard": typeof import("./src/routes/app.dashboard.tsx");
  "routes/app.sys.users": typeof import("./src/routes/app.sys.users/route.tsx");
  "routes/app.templates": typeof import("./src/routes/app.templates/route.tsx");
  "routes/app.sys.logs": typeof import("./src/routes/app.sys.logs/route.tsx");
  "routes/app.monitor": typeof import("./src/routes/app.monitor.tsx");
  "routes/app._index": typeof import("./src/routes/app._index.tsx");
  "routes/app.docker": typeof import("./src/routes/app.docker/route.tsx");
  "routes/app.iso": typeof import("./src/routes/app.iso.tsx");
  "routes/app.vms": typeof import("./src/routes/app.vms.tsx");
  "routes/app.vms.$uuid.console": typeof import("./src/routes/app.vms.$uuid.console.tsx");
};