// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/app": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/auth/register" | "/auth/login" | "/app";
  };
  "routes/_landing.tsx": {
    id: "routes/_landing";
    page: "/";
  };
  "routes/_landing._index.tsx": {
    id: "routes/_landing._index";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth" | "/auth/register" | "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_landing": typeof import("./src/routes/_landing.tsx");
  "routes/_landing._index": typeof import("./src/routes/_landing._index.tsx");
  "routes/auth": typeof import("./src/routes/auth.tsx");
  "routes/auth.register": typeof import("./src/routes/auth.register.tsx");
  "routes/auth.login": typeof import("./src/routes/auth.login.tsx");
  "routes/app": typeof import("./src/routes/app.tsx");
  "routes/app._index": typeof import("./src/routes/app._index.tsx");
};