// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sessions

import (
	"time"
)

type Log struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	Action       string    `json:"action"`
	Details      *string   `json:"details"`
	CreatedAt    time.Time `json:"created_at"`
	ServiceGroup string    `json:"service_group"`
	Level        string    `json:"level"`
}

type Notification struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Message   string    `json:"message"`
	Read      *bool     `json:"read"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type NotificationSetting struct {
	ID            int64     `json:"id"`
	Provider      string    `json:"provider"`
	Enabled       *bool     `json:"enabled"`
	WebhookUrl    *string   `json:"webhook_url"`
	NotifyOnError *bool     `json:"notify_on_error"`
	NotifyOnWarn  *bool     `json:"notify_on_warn"`
	NotifyOnInfo  *bool     `json:"notify_on_info"`
	Config        *string   `json:"config"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserSession struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	SessionToken string    `json:"session_token"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
