// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sessions

import (
	"context"
)

const deleteBySessionToken = `-- name: DeleteBySessionToken :exec
DELETE FROM user_sessions
WHERE
  session_token = ?
`

func (q *Queries) DeleteBySessionToken(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, deleteBySessionToken, sessionToken)
	return err
}

const getAllSessions = `-- name: GetAllSessions :many
SELECT
  id, user_id, session_token, created_at, updated_at
FROM
  user_sessions
`

// CREATE TABLE IF NOT EXISTS user_sessions (
//
//	id INTEGER PRIMARY KEY AUTOINCREMENT,
//	user_id INTEGER NOT NULL,
//	session_token TEXT NOT NULL UNIQUE,
//	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
//	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
//	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
//
// );
func (q *Queries) GetAllSessions(ctx context.Context) ([]UserSession, error) {
	rows, err := q.db.QueryContext(ctx, getAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  id, user_id, session_token, created_at, updated_at
FROM
  user_sessions
WHERE
  id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, id int64) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO
  user_sessions (user_id, session_token)
VALUES
  (?, ?) ON CONFLICT (session_token) DO
UPDATE
SET
  user_id = excluded.user_id,
  updated_at = CURRENT_TIMESTAMP RETURNING id, user_id, session_token, created_at, updated_at
`

type UpsertSessionParams struct {
	UserID       int64  `json:"user_id"`
	SessionToken string `json:"session_token"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, upsertSession, arg.UserID, arg.SessionToken)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
