// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package user

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (username, email, password, role)
VALUES
  (?, ?, ?, ?) RETURNING id, username, email, password, role, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE
  id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT
  id, username, email, password, role, created_at, updated_at
FROM
  users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByEmailOrUsername = `-- name: GetByEmailOrUsername :one
SELECT
  id, username, email, password, role, created_at, updated_at
FROM
  users
WHERE
  email = ?
  OR username = ?
`

type GetByEmailOrUsernameParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) GetByEmailOrUsername(ctx context.Context, arg GetByEmailOrUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getByEmailOrUsername, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBySessionToken = `-- name: GetBySessionToken :one
SELECT
  u.id, u.username, u.email, u.password, u.role, u.created_at, u.updated_at
FROM
  users u
  JOIN user_sessions us ON u.id = us.user_id
WHERE
  us.session_token = ?
`

func (q *Queries) GetBySessionToken(ctx context.Context, sessionToken string) (User, error) {
	row := q.db.QueryRowContext(ctx, getBySessionToken, sessionToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAndSessionByToken = `-- name: GetUserAndSessionByToken :one
SELECT
    u.id, u.username, u.email, u.password, u.role, u.created_at, u.updated_at, us.id, us.user_id, us.session_token, us.created_at, us.updated_at
FROM
  users u
  JOIN user_sessions us ON u.id = us.user_id
WHERE
  us.session_token = ?
`

type GetUserAndSessionByTokenRow struct {
	User        User        `json:"user"`
	UserSession UserSession `json:"user_session"`
}

func (q *Queries) GetUserAndSessionByToken(ctx context.Context, sessionToken string) (GetUserAndSessionByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAndSessionByToken, sessionToken)
	var i GetUserAndSessionByTokenRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.Password,
		&i.User.Role,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.UserSession.ID,
		&i.UserSession.UserID,
		&i.UserSession.SessionToken,
		&i.UserSession.CreatedAt,
		&i.UserSession.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :many
SELECT
  id, username, email, password, role, created_at, updated_at
FROM
  users
WHERE
  id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUserByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  username = ?,
  email = ?,
  role = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ? RETURNING id, username, email, password, role, created_at, updated_at
`

type UpdateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Role     string `json:"role"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET
  password = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ? RETURNING id, username, email, password, role, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	Password string `json:"password"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET
  role = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ? RETURNING id, username, email, password, role, created_at, updated_at
`

type UpdateUserRoleParams struct {
	Role string `json:"role"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.Role, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO
  users (username, email, password, role)
VALUES
  (?, ?, ?, ?) ON CONFLICT (email) DO
UPDATE
SET
  username = excluded.username,
  password = excluded.password,
  role = excluded.role,
  updated_at = CURRENT_TIMESTAMP RETURNING id, username, email, password, role, created_at, updated_at
`

type UpsertUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
