// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package user

import (
	"context"
)

const delete = `-- name: Delete :exec
DELETE FROM users
WHERE
  id = ?
`

func (q *Queries) Delete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT
  id, username, email, password, role, created_at, updated_at
FROM
  users
`

func (q *Queries) GetAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByEmailOrUsername = `-- name: GetByEmailOrUsername :one
SELECT
  id, username, email, password, role, created_at, updated_at
FROM
  users
WHERE
  email = ?
  OR username = ?
`

type GetByEmailOrUsernameParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) GetByEmailOrUsername(ctx context.Context, arg GetByEmailOrUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getByEmailOrUsername, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByID = `-- name: GetByID :many
SELECT
  id, username, email, password, role, created_at, updated_at
FROM
  users
WHERE
  id = ?
`

func (q *Queries) GetByID(ctx context.Context, id int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBySessionToken = `-- name: GetBySessionToken :one
SELECT
  u.id, u.username, u.email, u.password, u.role, u.created_at, u.updated_at
FROM
  users u
  JOIN user_sessions us ON u.id = us.user_id
WHERE
  us.session_token = ?
`

func (q *Queries) GetBySessionToken(ctx context.Context, sessionToken string) (User, error) {
	row := q.db.QueryRowContext(ctx, getBySessionToken, sessionToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsert = `-- name: Upsert :one
INSERT INTO
  users (username, email, password, role)
VALUES
  (?, ?, ?, ?) ON CONFLICT (email) DO
UPDATE
SET
  username = excluded.username,
  password = excluded.password,
  role = excluded.role,
  updated_at = CURRENT_TIMESTAMP RETURNING id, username, email, password, role, created_at, updated_at
`

type UpsertParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

func (q *Queries) Upsert(ctx context.Context, arg UpsertParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsert,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
